# Generated by Django 3.2.4 on 2021-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITIO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='description',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
