# Generated by Django 3.2.4 on 2021-06-30 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SITIO', '0002_alter_categorias_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='description',
            new_name='categoria',
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='imagenes/')),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=50)),
                ('categoria_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SITIO.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_products', models.ManyToManyField(to='SITIO.Productos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
