# Generated by Django 3.2.4 on 2021-07-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITIO', '0003_auto_20210630_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
