# Generated by Django 3.2.4 on 2021-07-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITIO', '0004_alter_productos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
