# Generated by Django 3.2.4 on 2021-07-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SITIO', '0005_alter_productos_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
