# Generated by Django 3.2.4 on 2021-07-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITIO', '0006_delete_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
