# Generated by Django 3.2.4 on 2021-07-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITIO', '0008_alter_productos_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='price',
            field=models.FloatField(max_length=3),
        ),
    ]
